<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.13.3 on win32)" generated="2025-05-19T15:40:56.285570" rpa="false" schemaversion="5">
<suite id="s1" name="LoginTest1" source="C:\RobotFrameworkBasics\POM\TestCases\LoginTest1.robot">
<test id="s1-t1" name="Invalid Login with ${username}" line="12">
<status status="FAIL" start="2025-05-19T15:40:56.591012" elapsed="0.001040">Test cannot be empty.</status>
</test>
<status status="FAIL" start="2025-05-19T15:40:56.288244" elapsed="0.305036"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="LoginTest1" id="s1" pass="0" fail="1" skip="0">LoginTest1</stat>
</suite>
</statistics>
<errors>
<msg time="2025-05-19T15:40:56.586259" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\RobotFrameworkBasics\POM\TestCases\LoginTest1.robot", line 0</msg>
<msg time="2025-05-19T15:40:56.586434" level="ERROR">In source file:
  File "C:\RobotFrameworkBasics\POM\TestCases\..\Resources\LoginData.csv", line 0</msg>
<msg time="2025-05-19T15:40:56.589621" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ValueError: Unassigned requiered argument detected: ${username}.</msg>
</errors>
</robot>
